
name: 'Generate Cache Manager'
description: 'Creates a simple cache clearing page'

runs:
  using: "composite"
  steps:
    - name: Create clear-cache.html file
      shell: bash
      run: |
        echo "<!DOCTYPE html><html><head><title>Clear Cache</title></head><body><h1>Clear Cache</h1><button onclick=\"localStorage.clear(); sessionStorage.clear(); alert('Cache cleared!'); window.location.reload();\">Clear Cache</button></body></html>" > dist/clear-cache.html
