
name: 'Verify Deployment'
description: 'Simple verification of deployment files'

runs:
  using: "composite"
  steps:
    - name: Verify deployment
      shell: bash
      run: |
        echo "=== DEPLOYMENT VERIFICATION ==="
        echo "Checking critical files exist in the build folder"
        ls -la dist/
