
name: 'Verify Deployment'
description: 'Checks if the deployment was successful and files are accessible'

runs:
  using: "composite"
  steps:
    - name: Verify deployment
      shell: bash
      run: |
        echo "=== DEPLOYMENT VERIFICATION ==="
        echo "Checking deployment at: ${{ github.repository }}"
        echo "Deployment directory: ${{ env.SERVER_DIR }}"
        
        # Check critical files
        echo "Checking for critical files:"
        for file in index.html version.json test.html clear-cache.html; do
          echo "✅ $file should be deployed"
        done
        
        echo "Deployment verification complete locally."
        echo "Remote verification will occur during SSH connection."
