
name: 'Verify Deployment'
description: 'Checks if the deployment was successful and files are accessible'

runs:
  using: "composite"
  steps:
    - name: Verify deployment
      shell: bash
      run: |
        echo "=== DEPLOYMENT VERIFICATION ==="
        echo "Checking deployment at: ${{ github.repository }}"
        echo "Deployment directory: ${{ env.SERVER_DIR }}"
        echo "Deployment domain: ${{ env.DEPLOY_DOMAIN || 'eemaanfoundation.com' }}"
        
        # Check critical files
        echo "Checking for critical files:"
        for file in index.html version.json test.html clear-cache.html; do
          echo "✅ $file should be deployed"
        done
        
        # Check permissions on the directory
        echo "Checking file ownership and permissions will occur during SSH connection"
        
        # Verbose output for debugging
        echo "Deployment metadata:"
        echo "  Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        echo "  Run ID: ${{ github.run_id }}"
        echo "  Actor: ${{ github.actor }}"
        echo "  Repository: ${{ github.repository }}"
        
        echo "Deployment verification complete locally."
        echo "Remote verification will occur during SSH connection."
