
name: 'Generate .htaccess File'
description: 'Creates simple .htaccess file for SPA routing'

runs:
  using: "composite"
  steps:
    - name: Create .htaccess file
      shell: bash
      run: |
        echo '<IfModule mod_rewrite.c>' > dist/.htaccess
        echo '  RewriteEngine On' >> dist/.htaccess
        echo '  RewriteBase /' >> dist/.htaccess
        echo '  RewriteRule ^index\.html$ - [L]' >> dist/.htaccess
        echo '  RewriteCond %{REQUEST_FILENAME} !-f' >> dist/.htaccess
        echo '  RewriteCond %{REQUEST_FILENAME} !-d' >> dist/.htaccess
        echo '  RewriteRule . /index.html [L]' >> dist/.htaccess
        echo '</IfModule>' >> dist/.htaccess
