
name: 'Generate Test Page'
description: 'Creates simple test.html file'

runs:
  using: "composite"
  steps:
    - name: Create test HTML file
      shell: bash
      run: |
        echo "<!DOCTYPE html><html><head><title>Test Page</title></head><body><h1>Test Page</h1><p>Deployment successful!</p></body></html>" > dist/test.html
