
name: 'Generate Deployment Files'
description: 'Orchestrates the creation of necessary deployment files'
author: 'Eemaan Foundation'
branding:
  icon: 'terminal'
  color: 'green'

runs:
  using: "composite"
  steps:
    - name: Generate .htaccess file
      uses: ./.github/actions/generate-htaccess
      
    - name: Generate test page
      uses: ./.github/actions/generate-test-page
      
    - name: Generate cache manager
      uses: ./.github/actions/generate-cache-manager
      
    - name: Generate version info
      uses: ./.github/actions/generate-version-info
