
name: 'Generate Deployment Files'
description: 'Creates basic deployment files'

runs:
  using: "composite"
  steps:
    - name: Generate files
      shell: bash
      run: |
        # Generate version.json file
        echo "{\"version\":\"${{ github.sha }}\",\"buildTime\":\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" > dist/version.json
        
        # Generate basic .htaccess file
        echo "<IfModule mod_rewrite.c>" > dist/.htaccess
        echo "  RewriteEngine On" >> dist/.htaccess
        echo "  RewriteBase /" >> dist/.htaccess
        echo "  RewriteRule ^index\.html$ - [L]" >> dist/.htaccess
        echo "  RewriteCond %{REQUEST_FILENAME} !-f" >> dist/.htaccess
        echo "  RewriteCond %{REQUEST_FILENAME} !-d" >> dist/.htaccess
        echo "  RewriteRule . /index.html [L]" >> dist/.htaccess
        echo "</IfModule>" >> dist/.htaccess
