
name: 'Generate Version Info'
description: 'Creates version.json file for cache validation'
author: 'Eemaan Foundation'
branding:
  icon: 'tag'
  color: 'purple'

runs:
  using: "composite"
  steps:
    - name: Generate version.json
      shell: bash
      run: |
        echo "{\"version\":\"${{ github.sha }}\",\"buildTime\":\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" > dist/version.json
