
name: 'Generate Version Info'
description: 'Creates version.json file for cache validation'
author: 'Eemaan Foundation'
branding:
  icon: 'tag'
  color: 'purple'

runs:
  using: "composite"
  steps:
    - name: Ensure version.json exists
      shell: bash
      run: |
        CURRENT_TIME=$(date +%s)
        DEPLOY_ID="${{ github.run_id }}-${CURRENT_TIME}"
        
        if [ ! -f dist/version.json ]; then
          echo "{\"version\":\"${{ github.sha }}\",\"buildTime\":\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\",\"timestamp\":$CURRENT_TIME,\"runId\":\"${{ github.run_id }}\",\"deployId\":\"$DEPLOY_ID\",\"buildNumber\":\"${{ github.run_number }}\"}" > dist/version.json
          echo "Created version.json:"
          cat dist/version.json
        else
          echo "Updating existing version.json:"
          # Parse existing file and update timestamp
          jq ".timestamp = $CURRENT_TIME | .buildTime = \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\" | .runId = \"${{ github.run_id }}\" | .deployId = \"$DEPLOY_ID\"" dist/version.json > dist/version.json.new
          mv dist/version.json.new dist/version.json
          cat dist/version.json
        fi
        
        # Create a clear text version for easy debugging
        mkdir -p dist/debug
        echo "Deployment ID: $DEPLOY_ID" > dist/debug/version-info.txt
        echo "Build time: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> dist/debug/version-info.txt
        echo "Commit: ${{ github.sha }}" >> dist/debug/version-info.txt
        echo "Run ID: ${{ github.run_id }}" >> dist/debug/version-info.txt
        echo "Timestamp: $CURRENT_TIME" >> dist/debug/version-info.txt
