
name: Build & Deploy to Web Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build
        env:
          # Add timestamp to ensure unique builds
          BUILD_TIMESTAMP: ${{ github.run_number }}-${{ github.run_id }}-${{ github.sha }}-${{ github.event.repository.updated_at }}
        
      - name: Generate deployment files
        uses: ./.github/actions/generate-deployment-files
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      SERVER_DIR: /public_html
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      # Force timestamp to be updated for cache invalidation
      - name: Update version timestamp
        run: |
          CURRENT_TIME=$(date +%s)
          echo "{\"version\":\"${{ github.sha }}\",\"buildTime\":\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\",\"timestamp\":$CURRENT_TIME,\"runId\":\"${{ github.run_id }}\"}" > dist/version.json
          echo "Version file updated with timestamp: $CURRENT_TIME"
          cat dist/version.json

      - name: Deploy files to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "dist/*"
          target: "${{ env.SERVER_DIR }}"
          strip_components: 1
          overwrite: true

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            echo "=== DEPLOYMENT VERIFICATION ==="
            echo "Checking deployment at: ${{ env.SERVER_DIR }}"
            
            # Check if directory exists
            if [ ! -d "${{ env.SERVER_DIR }}" ]; then
              echo "ERROR: Deployment directory does not exist!"
              exit 1
            fi
            
            # Check for critical files
            echo "Checking for critical files in ${{ env.SERVER_DIR }}:"
            for file in index.html version.json test.html clear-cache.html; do
              if [ -f "${{ env.SERVER_DIR }}/$file" ]; then
                echo "✅ $file exists"
              else
                echo "❌ $file is missing!"
              fi
            done
            
            # Force clear server-side caches if any
            echo "Touching files to ensure freshness..."
            touch ${{ env.SERVER_DIR }}/index.html
            touch ${{ env.SERVER_DIR }}/version.json
            
            # Create a deployment marker with current time to force cache invalidation
            echo "Deployment completed at $(date)" > ${{ env.SERVER_DIR }}/deployment-marker.txt
            echo "GitHub Run ID: ${{ github.run_id }}" >> ${{ env.SERVER_DIR }}/deployment-marker.txt
            echo "Timestamp: $(date +%s)" >> ${{ env.SERVER_DIR }}/deployment-marker.txt
            
            echo "Listing directory contents:"
            ls -la ${{ env.SERVER_DIR }} | head -20
            
            echo "Deployment verification complete."

      - name: Deployment summary
        uses: ./.github/actions/deployment-summary
