
name: Build & Deploy to Web Server via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build
        
      # Create .htaccess file for SPA routing
      - name: Create .htaccess file for SPA routing
        run: |
          echo '<IfModule mod_rewrite.c>' > dist/.htaccess
          echo '  RewriteEngine On' >> dist/.htaccess
          echo '  RewriteBase /' >> dist/.htaccess
          echo '  RewriteRule ^index\.html$ - [L]' >> dist/.htaccess
          echo '  RewriteCond %{REQUEST_FILENAME} !-f' >> dist/.htaccess
          echo '  RewriteCond %{REQUEST_FILENAME} !-d' >> dist/.htaccess
          echo '  RewriteRule . /index.html [L]' >> dist/.htaccess
          echo '</IfModule>' >> dist/.htaccess

      - name: List build output
        run: |
          echo "=== Listing build output ==="
          ls -la dist/
          echo "=== End of listing ==="

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: ${{ secrets.SERVER_DIR || '/public_html/quran/' }}
          dry-run: false
          dangerous-clean-slate: true
          log-level: verbose
